export const markup = `
<header class="header"><a class="brand" href="./"><span class="brand-mark">✳</span> РАЗЛОМ<span class="brand-en">RIFT</span></a><span class="edition">MOTION <span>/</span> ПРОБУЖДЕНИЕ</span><button id="help" class="text-button" aria-expanded="false">Печати / помощь</button><button id="fullscreen" class="text-button">⤢ На весь экран</button><button id="sound" class="sound-toggle" aria-pressed="true">♫ ЗВУК ВКЛ.</button></header>
<main><section class="intro"><div><p class="eyebrow">ТВОЯ РУКА — ТВОЁ ОРУЖИЕ</p><h1>По ту сторону <em>обычного.</em></h1><p class="lead">Лови чужую магию. Рассекай тьму. Защити ядро от того, что по ту сторону.</p></div><div class="chapter"><span id="best-score">0</span><small>ЛИЧНЫЙ РЕКОРД</small></div></section>
<div class="workspace"><section class="arena" aria-label="Арена разлома">
<div class="arena-top"><span><i class="live-dot"></i><span id="arena-status">ОЖИДАНИЕ МАГА</span></span><span id="counter">ТРИ ТЕХНИКИ · ОДНА ТЕРРИТОРИЯ</span></div>
<canvas id="scene" aria-label="Арена, снаряды, кристаллы и босс"></canvas>
<div id="battle-hud" class="combat-hud" hidden><div class="hud-stats"><div><small>ЯДРО</small><strong id="health">100%</strong></div><div><small>ВРЕМЯ</small><strong id="time-left">2:30</strong></div><div><small>ОЧКИ</small><strong id="score">0</strong></div><div><small>СЕРИЯ</small><strong id="combo">×0</strong></div></div><div class="boss-label"><span id="boss-name">ЗАВЕСА</span><span id="boss-state">ПЕРВЫЕ ТРЕЩИНЫ</span></div><div class="boss-track"><div id="boss-fill"></div></div><div class="resource-row"><span>ЩИТ <b id="shield-value">100%</b></span><span>ТЕРРИТОРИЯ <b id="energy-value">0%</b></span></div></div>
<div id="cinematic" class="cinematic" hidden><small id="cinematic-kicker">РАЗЛОМ МЕНЯЕТСЯ</small><strong id="cinematic-title"></strong></div>
<div id="countdown" class="countdown" hidden><span id="countdown-number">3</span><small>ПРИГОТОВЬСЯ</small></div>
<div id="battle-message" class="battle-message" role="status" hidden></div>
<div id="portal-caption" class="portal-caption"><span>РАЗЛОМ</span><small>ПРОСТРАНСТВО ПОМНИТ ТВОИ РУКИ</small></div>
<div id="awakening" class="awakening" hidden><p class="eyebrow">ПЕРВАЯ ПЕЧАТЬ</p><h2 id="awakening-title">Он уже здесь.</h2><div class="opening-hands" aria-label="Два поднятых пальца на каждой руке"><span>✌</span><i>◇</i><span>✌</span></div><p id="awakening-hands-status" class="hands-status"></p><p id="awakening-hint">Он почувствовал твоё присутствие.</p><div class="progress-track"><div id="awakening-progress"></div></div><div class="intro-actions"><button id="skip-intro" class="text-button" hidden>К обучению ↗</button><button id="skip-training" class="text-button" hidden>Сразу в бой ↗</button></div></div>
<div id="start-panel" class="start-panel"><button id="start" class="primary">Войти в разлом <span>↗</span></button><p id="setup-note" role="status">Разреши камеру · освободи место для руки</p><small>Кадры остаются на устройстве. Управление — движениями.</small></div>
<div id="calibration" class="calibration-panel" hidden><p class="eyebrow">НАСТРОЙКА ПОД ТЕБЯ</p><h2>Найди свой размах.</h2><div class="calibration-map"><div id="calibration-range"></div><i id="calibration-cursor"></i><span>↔ ↕</span></div><p id="calibration-hint">Раскрой ладонь. Медленно проведи ею влево, вправо, вверх и вниз — насколько тебе удобно.</p><div class="progress-track"><div id="calibration-progress"></div></div><button id="default-calibration" class="text-button">Использовать стандартный размах</button><small>Когда рамка станет зелёной, сожми кулак для подтверждения.</small></div>
<div id="lesson-demo" class="lesson-demo" hidden><p id="lesson-number" class="eyebrow"></p><h2 id="lesson-title"></h2><div id="lesson-animation"></div><p id="lesson-instruction"></p><div id="lesson-arm" class="lesson-arm" role="status"></div><div class="lesson-arm-track"><div id="lesson-arm-progress"></div></div></div>
<div id="feedback" class="feedback" hidden><div id="hand-readout"><span id="primary-hand-state"></span><span id="second-hand-state"></span></div><ol id="ritual-steps" hidden><li></li><li></li><li></li></ol><div class="feedback-label"><span id="spell-name"></span><span id="progress-label"></span></div><p id="hint" role="status" aria-live="polite"></p><div class="progress-track"><div id="progress-fill"></div></div></div>
<div id="result" class="result" hidden><span class="result-mark" id="result-mark">✳</span><p class="eyebrow" id="result-eyebrow"></p><h2 id="result-title"></h2><p id="result-description"></p><div class="result-stats"><div><strong id="result-value">3 / 3</strong><small id="result-value-label">СПОСОБНОСТИ</small></div><div><strong id="duration">—</strong><small id="duration-label">РЕКОРД</small></div></div><div id="report" class="report" hidden><p id="result-detail"></p><strong id="advice-title"></strong><p id="advice-detail"></p><button id="drill" class="text-button">Потренировать это действие ↗</button></div><button id="restart" class="primary">Войти в разлом <span>↗</span></button><button id="retrain" class="text-button">Повторить обучение</button><small id="restart-hint">Убери руку из кадра, затем покажи открытую ладонь.</small><div class="result-gesture-track"><div id="restart-progress"></div></div></div>
<div class="arena-bottom"><span id="tracking-status">✧ СВЯЗЬ НЕ УСТАНОВЛЕНА</span><button id="stop" hidden>Выключить камеру</button></div>
</section><aside><section class="spellbook"><div class="section-title"><h2>Твоя магия</h2><span>03 + ∞</span></div>
<div class="spell" data-step="0"><div class="spell-icon">◈</div><div><span class="spell-number">01 / СЖАТИЕ</span><h3>Сожми пространство</h3><p>Покажи ладонь. Кулак накапливает силу.<br> Раскрой ладонь — выпусти волну.</p></div><span class="spell-check"></span></div>
<div class="spell" data-step="1"><div class="spell-icon">⬡</div><div><span class="spell-number">02 / ОТРАЖЕНИЕ</span><h3>Прикрой ядро</h3><p>Раскрытая ладонь на пути атаки.<br> Точный момент даёт отражение.</p></div><span class="spell-check"></span></div>
<div class="spell" data-step="2"><div class="spell-icon">ϟ</div><div><span class="spell-number">03 / РАЗРЕЗ</span><h3>Рассеки кристалл</h3><p>Два поднятых пальца → взмах через цель.<br> Дождись, когда загорится печать.</p></div><span class="spell-check"></span></div>
<div class="spell secret-spell" data-step="3"><span>∞</span><div><strong>Расширение территории</strong><p>Две ладони рядом → круг щипком → разведи ладони.</p></div><span class="spell-check"></span></div></section>
<div class="practice-links"><button class="text-button" data-practice="swipe">Тренировать разрез ✌</button><button class="text-button" data-practice="domain">Тренировать круг / территорию</button></div><button id="recalibrate" class="text-button" hidden>Настроить размах заново</button><section class="camera-card"><div class="section-title"><h2>Твой проводник</h2><span id="camera-badge">КАМЕРА ВЫКЛ.</span></div><div class="camera-view"><video id="camera" autoplay muted playsinline></video><canvas id="skeleton"></canvas><div id="camera-placeholder"><span>◎</span><p>Здесь появится твоя рука</p></div></div><p class="camera-tip">Две руки — первая печать и территория.<br>Потеря руки ставит бой на паузу.</p></section>
<section class="progress-card"><span class="eyebrow">ТВОЙ ПРОГРЕСС</span><p id="history">Первый разлом ещё впереди.</p></section></aside></div>
<footer><span>ADMIT HACKATHON / 2026</span><span>Управляй магией. Своими руками.</span><span>РАЗЛОМ — ПРОБУЖДЕНИЕ</span></footer></main>`;
