import { icon } from "./icons";
export const markup = `
<header class="header"><a class="brand" href="./"><span class="brand-mark">${icon("rift")}</span> РАЗЛОМ<span class="brand-en">RIFT</span></a><span class="edition">MOTION <span>/</span> ПРОБУЖДЕНИЕ</span><button id="help" class="text-button" aria-expanded="false">Печати / помощь</button><button id="fullscreen" class="text-button">${icon("fullscreen")}<span data-label>На весь экран</span></button><button id="sound" class="sound-toggle" aria-pressed="true">${icon("sound")}<span data-label>ЗВУК ВКЛ.</span></button></header>
<main><section class="intro"><div><p class="eyebrow">ТВОЯ РУКА — ТВОЁ ОРУЖИЕ</p><h1>По ту сторону <em>обычного.</em></h1><p class="lead">Лови чужую магию. Рассекай тьму. Защити ядро от того, что по ту сторону.</p></div><div class="chapter"><span id="best-score">0</span><small>ЛИЧНЫЙ РЕКОРД</small></div></section>
<div class="workspace"><section class="arena" aria-label="Арена разлома">
<div class="arena-top"><span><i class="live-dot"></i><span id="arena-status">ОЖИДАНИЕ МАГА</span></span><span id="counter">ТВОИ РУКИ · ТВОЯ МАГИЯ</span></div>
<canvas id="scene" aria-label="Арена, снаряды, кристаллы и босс"></canvas>
<div id="battle-hud" class="combat-hud" hidden><div class="hud-stats"><div><small>ЯДРО</small><strong id="health">100%</strong></div><div><small>ВРЕМЯ</small><strong id="time-left">1:05</strong></div><div><small>ОЧКИ</small><strong id="score">0</strong></div><div><small>СЕРИЯ</small><strong id="combo">×0</strong></div></div><div class="boss-label"><span id="boss-name">ЗАВЕСА</span><span id="boss-state">ПЕРВЫЕ ТРЕЩИНЫ</span></div><div class="boss-track"><div id="boss-fill"></div></div><div class="resource-row"><span>ЩИТ <b id="shield-value">100%</b></span><span>ТЕРРИТОРИЯ <b id="energy-value">30%</b></span></div><p id="extra-status" class="extra-status"></p></div>
<div id="cinematic" class="cinematic" hidden><small id="cinematic-kicker">РАЗЛОМ МЕНЯЕТСЯ</small><strong id="cinematic-title"></strong></div>
<div id="countdown" class="countdown" hidden><span id="countdown-number">3</span><small>ПРИГОТОВЬСЯ</small></div>
<div id="battle-message" class="battle-message" role="status" hidden></div>
<div id="portal-caption" class="portal-caption"><span>РАЗЛОМ</span><small>ПРОСТРАНСТВО ПОМНИТ ТВОИ РУКИ</small></div>
<div id="preparation" class="preparation" role="dialog" aria-modal="true" aria-labelledby="preparation-title" hidden><div class="preparation-card"><p id="preparation-number" class="eyebrow"></p><div id="preparation-art"></div><h2 id="preparation-title"></h2><p id="preparation-description"></p><div class="preparation-confirm"><span class="palm-confirm">${icon("palm")}</span><span id="preparation-hint" role="status"></span></div><div class="progress-track"><div id="preparation-progress"></div></div><div class="preparation-actions"><button id="preparation-next" class="text-button">Продолжить кнопкой ${icon("arrow")}</button><button id="preparation-skip" class="text-button" hidden>Я уже готов ${icon("arrow")}</button></div><small>Рекомендуем Google Chrome · камера обрабатывается на устройстве</small></div></div>
<div id="mastery" class="mastery" role="dialog" aria-modal="true" aria-labelledby="mastery-title" tabindex="-1" hidden>
<div class="mastery-card"><p id="mastery-kicker" class="eyebrow">ТЕХНИКА ОСВОЕНА</p><div class="mastery-emblem"><span id="mastery-emblem-icon">${icon("seal")}</span></div><p id="mastery-number" class="mastery-number"></p><h2 id="mastery-title"></h2><div id="mastery-art"></div><p id="mastery-description"></p><div class="mastery-confirm">${icon("palm")}<span id="mastery-hint" role="status">Сожми кулак, затем раскрой ладонь для подтверждения.</span></div><div class="progress-track"><div id="mastery-progress"></div></div><small>Твоё время. Продолжение — только по жесту.</small></div></div>
<div id="rest-panel" class="rest-panel" hidden><p class="eyebrow">ЯДРО ПРИКРЫВАЕТ ТЕБЯ</p><h2>Выдохни.</h2><p>Опусти руки и расслабь плечи.</p><strong id="rest-countdown">4</strong><div id="rest-art" class="rest-art" aria-hidden="true"></div><p id="rest-unlock"></p></div>
<div id="awakening" class="awakening" hidden><p class="eyebrow">ПЕРВАЯ ПЕЧАТЬ</p><h2 id="awakening-title">Он уже здесь.</h2><div class="opening-hands" aria-label="Два поднятых пальца на каждой руке"><span>${icon("sign")}</span><i>${icon("seal")}</i><span>${icon("sign")}</span></div><p id="awakening-hands-status" class="hands-status"></p><p id="awakening-hint">Он почувствовал твоё присутствие.</p><div class="progress-track"><div id="awakening-progress"></div></div><div class="intro-actions"><button id="skip-intro" class="text-button" hidden>К обучению ${icon("arrow")}</button><button id="skip-training" class="text-button" hidden>Сразу в бой ${icon("arrow")}</button></div></div>
<div id="start-panel" class="start-panel"><button id="start" class="primary">${icon("arrow")}<span data-label>Войти в разлом</span></button><p class="setup-advice">Лучше играть в Google Chrome. Перед началом поможем настроиться.</p><p id="setup-note" role="status">Разреши доступ к камере, чтобы начать.</p><small>Кадры остаются на устройстве. Управление — движениями.</small></div>
<div id="calibration" class="calibration-panel" hidden><p class="eyebrow">НАСТРОЙКА ПОД ТЕБЯ</p><h2>Найди свой размах.</h2><div class="calibration-map"><div id="calibration-range"></div><i id="calibration-cursor"></i><span>${icon("move")}</span></div><p id="calibration-hint">Раскрой ладонь. Медленно проведи ею влево, вправо, вверх и вниз — насколько тебе удобно.</p><div class="progress-track"><div id="calibration-progress"></div></div><button id="default-calibration" class="text-button">Использовать стандартный размах</button><small>Когда рамка станет зелёной, сожми кулак для подтверждения.</small></div>
<div id="lesson-demo" class="lesson-demo" hidden><p id="lesson-number" class="eyebrow"></p><h2 id="lesson-title"></h2><div id="lesson-animation"></div><p id="lesson-instruction"></p><div id="lesson-arm" class="lesson-arm" role="status"></div><div class="lesson-arm-track"><div id="lesson-arm-progress"></div></div></div>
<div id="feedback" class="feedback" hidden><div id="live-gesture-art" class="live-gesture-art" aria-hidden="true"></div><div id="hand-readout"><span id="primary-hand-state"></span><span id="second-hand-state"></span></div><ol id="ritual-steps" hidden><li></li><li></li><li></li></ol><div class="feedback-label"><span id="spell-name"></span><span id="progress-label"></span></div><p id="hint" role="status" aria-live="polite"></p><div class="progress-track"><div id="progress-fill"></div></div></div>
<div id="result" class="result" hidden><span class="result-mark" id="result-mark">${icon("rift")}</span><p class="eyebrow" id="result-eyebrow"></p><h2 id="result-title"></h2><p id="result-description"></p><div class="result-stats"><div><strong id="result-value">3 / 3</strong><small id="result-value-label">СПОСОБНОСТИ</small></div><div><strong id="duration">—</strong><small id="duration-label">РЕКОРД</small></div></div><div id="report" class="report" hidden><p id="result-detail"></p><strong id="advice-title"></strong><p id="advice-detail"></p><button id="drill" class="text-button">Потренировать это действие ${icon("arrow")}</button></div><button id="restart" class="primary">${icon("arrow")}<span data-label>Войти в разлом</span></button><button id="retrain" class="text-button">Повторить обучение</button><small id="restart-hint">Убери руку из кадра, затем покажи открытую ладонь.</small><div class="result-gesture-track"><div id="restart-progress"></div></div></div>
<div class="arena-bottom"><span id="tracking-status">${icon("seal")}<span data-label>СВЯЗЬ НЕ УСТАНОВЛЕНА</span></span><button id="stop" hidden>Выключить камеру</button></div>
</section><aside><section class="spellbook"><div class="section-title"><h2>Твоя магия</h2><span>06 ПЕЧАТЕЙ</span></div>
<div class="spell" data-step="0"><div class="spell-icon">${icon("seal")}</div><div><span class="spell-number">01 / СЖАТИЕ</span><h3>Сожми пространство</h3><p>Покажи ладонь. Кулак накапливает силу.<br> Раскрой ладонь — выпусти волну.</p></div><span class="spell-check"></span></div>
<div class="spell" data-step="1"><div class="spell-icon">${icon("shield")}</div><div><span class="spell-number">02 / ОТРАЖЕНИЕ</span><h3>Прикрой ядро</h3><p>Раскрытая ладонь на пути атаки.<br> Точный момент даёт отражение.</p></div><span class="spell-check"></span></div>
<div class="spell" data-step="2"><div class="spell-icon">${icon("slash")}</div><div><span class="spell-number">03 / РАЗРЕЗ</span><h3>Рассеки кристалл</h3><p>Два поднятых пальца → взмах через цель.<br> Дождись, когда загорится печать.</p></div><span class="spell-check"></span></div>
<div class="spell secret-spell" data-step="3"><span>${icon("seal")}</span><div><strong>Расширение территории</strong><p>Два пальца на обеих руках → раскрой обе ладони.</p></div><span class="spell-check"></span></div><div class="extra-spell" data-extra="spear"><span class="eyebrow">ОТКРОЕТСЯ ЧЕРЕЗ 12 С БОЯ</span><h3>Копьё разлома</h3><div data-art="spear"></div><p>Указательный и большой раскрыты, остальные согнуты. Наведи курсор на цель и удержи 0,6 с. Пробивает броню. Перезарядка 3,5 с.</p></div><div class="extra-spell" data-extra="bind"><span class="eyebrow">ОТКРОЕТСЯ С ПРОБУЖДЕНИЕМ БОССА</span><h3>Печать оков</h3><div data-art="bind"></div><p>Кулак и раскрытая ладонь рядом, без перекрытия. Удержи 0,65 с. Останавливает снаряды на 3 с. Перезарядка 10 с. Луч продолжает заряжаться.</p></div></section>
<div class="practice-links"><button class="text-button" data-practice="swipe">Тренировать разрез</button><button class="text-button" data-practice="domain">Тренировать территорию</button></div><button id="show-preparation" class="text-button">Подготовка к игре</button><button id="recalibrate" class="text-button" hidden>Настроить размах заново</button><section class="camera-card"><div class="section-title"><h2>Твой проводник</h2><span id="camera-badge">КАМЕРА ВЫКЛ.</span></div><div class="camera-view"><video id="camera" autoplay muted playsinline></video><canvas id="skeleton"></canvas><div id="camera-placeholder"><span>${icon("camera")}</span><p>Здесь появится твоя рука</p></div></div><p class="camera-tip">Если руки обрезаются, сядь чуть дальше от камеры.<br>Две руки — первая печать и территория.<br>Потеря руки ставит бой на паузу.</p></section>
<section class="progress-card"><p id="detector-stats">Отклик рук: камера выключена</p><p id="detector-details"></p><span class="eyebrow">ТВОЙ ПРОГРЕСС</span><p id="history">Первый разлом ещё впереди.</p></section></aside></div>
<footer><span>ADMIT HACKATHON / 2026</span><span>Управляй магией. Своими руками.</span><span>РАЗЛОМ — ПРОБУЖДЕНИЕ</span></footer></main>`;
